[package]
name = "nixman"
version = "0.3.5"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
askama = "0.12.1"
clap = {version = "4.5.7", features = ["derive"]}
regex = "1.10.5"

